version: "1"
services:
  - type: web
    name: my-app-name
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromService: mysql # Ensure this references the exact name of your database service

  - type: pserv
    name: mysql
    runtime: docker
    repo: https://github.com/render-examples/mysql
    plan: starter
    envVars:
      - fromGroup: mysql
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    autoDeploy: false
